### ISSUE TITLE
Engines crash the game when placed side-by-side.

### ISSUE THREAD

**Issue by SkywolfDragon** [JackRaidenPH/BuildCraftRF#2]
When placed side by side, engines turn to face each other, which immediately crashes the game. This also prevents the loading of the world where that happens; it crashes on loading into the world.

**Comment by jackraidenph** [comment]
Thank you for letting me know, will be fixed soon

**Comment by jackraidenph** [comment]
Fixed in 73a7fd595e4b9c22cf89901f0305cbf3464a7957
